spring.application.name=messaging-service

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=admin
spring.data.mongodb.username=paula
spring.data.mongodb.password=123

logging.level.root=INFO
logging.level.org.springframework.web.socket=DEBUG
